import random, importlib
jp  = importlib.import_module("jeff-phrasing")

simple_starters_keys = jp.SIMPLE_STARTERS.keys()
simple_pronouns_keys = jp.SIMPLE_PRONOUNS.keys()
simple_structures_keys = jp.SIMPLE_STRUCTURES.keys()

# Ender format: base_ender: (past_form, suffix_form, past_suffix_form)
enders = { 
    "RB": ("RBD", None, None),
    "B": ("BD", "BT", "BTD"),
    "RPBG": ("RPBGD", "RPBGT", "RPBGTD"),
    "BL": ("BLD", "BLT", "BLTD"),
    "RBLG": ("RBLGD", None, None),
    "BGS": ("BGSZ", None, None),
    "RZ": ("RDZ", None, None),
    "BG": ("BGD", "BGT", "BGTD"),
    "RP": ("RPD", "RPT", "RPTD"),
    "PGS": ("PGSZ", "PGTS", "PGTSDZ"),
    "LT": ("LTD", "LTS", "LTSDZ"),
    "PBLG": ("PBLGD", "PBLGT", "PBLGTD"),
    "RG": ("RGD", "RGT", "RGTD"),
    "GS": ("GSZ", "GTS", "GTSDZ"),
    "GZ": ("GDZ", None, None),
    "G": ("GD", "GT", "GTD"),
    "T": ("TD", "TS", "TSDZ"),
    "PZ": ("PDZ", None, None),
    "PG": ("PGD", "PGT", "PGTD"),
    "RPS": ("RPSZ", "RPTS", "RPTSDZ"),
    "PLG": ("PLGD", "PLGT", "PLGTD"),
    "PBLGSZ": ("PBLGTSDZ", None, None),
    "PBGS": ("PBGSZ", None, None),
    "PB": ("PBD", "PBT", "PBTD"),
    "RPBS": ("RPBSZ", "RPBTS", "RPBTSDZ"),
    "LGZ": ("LGDZ", None, None),
    "LS": ("LSZ", None, None),
    "BLG": ("BLGD", "BLGT", "BLGTD"),
    "LZ": ("LDZ", None, None),
    "L": ("LD", None, None),
    "LG": ("LGD", "LGT", "LGTD"),
    "RPBL": ("RPBLD", "RPBLT", "RPBLTD"),
    "PL": ("PLD", "PLT", "PLTD"),
    "PBL": ("PBLD", "PBLT", "PBLTD"),
    "PBLS": ("PBLSZ", None, None),
    "PLZ": ("PLDZ", None, None),
    "PBLGS": (None, "PBLGTS", None),
    "RPG": ("RPGD", "RPGT", "RPGTD"),
    "PS": ("PSZ", "PTS", "PTSDZ"),
    "RS": ("RSZ", None, None),
    "RLG": ("RLGD", None, None),
    "RL": ("RLD", None, None),
    "RLS": ("RLSZ", "RLTS", "RLTSDZ"),
    "RPL": ("RPLD", "RPLT", "RPLTD"),
    "RPLS": ("RPLSZ", None, None),
    "R": ("RD", None, None),
    "BS": ("BSZ", "BTS", "BTSDZ"),
    "S": ("SZ", None, None),
    "BLS": ("BLSZ", None, None),
    "PLS": ("PLSZ", "PLTS", "PLTSDZ"),
    "RBL": ("RBLD", None, None),
    "RBZ": ("RBDZ", None, None),
    "RBT": ("RBTD", None, None),
    "RLT": ("RLTD", None, None),
    "PBG": ("PBGD", "PBGT", "PBGTD"),
    "RT": ("RTD", "RTS", "RTSDZ"),
    "Z": ("DZ", "TZ", "TDZ"),
    "P": ("PD", "PT", "PTD"),
    "RBGZ": ("RBGSZ", None, None),
    "RBS": ("RBSZ", "RBTS", "RBTSDZ"),
    "RBG": ("RGBD", "RBGT", "RBGTD")
}